const products = {
  product: [
    {
      id: 1,
      brand: "Dennis Lingo",
      name: "Men Slim Fit Casual TShirt",
      image: "Product_1.jpeg",
      Price: 699,
      quantity: 1,
      amount: 0,
    },
    {
      id: 2,
      brand: "H&M",
      name: "Tie-belt shirt dress",
      image: "Product_2.jpeg",
      Price: 469,
      quantity: 1,
      amount: 0,
    },
    {
      id: 3,
      brand: "Ahika",
      name: "Denim dungaree dress",
      image: "Product_3.jpeg",
      Price: 284,
      quantity: 1,
      amount: 0,
    },
    {
      id: 4,
      brand: "DILLINGER",
      name: "V Neck Dress",
      image: "Product_4.jpeg",
      Price: 714,
      quantity: 1,
      amount: 0,
    },
    {
      id: 5,
      brand: "U & F",
      name: "Puff-sleeved crêpe dress",
      image: "Product_5.jpeg",
      Price: 129,
      quantity: 1,
      amount: 0,
    },
    {
      id: 6,
      brand: "Difference of Opinion",
      name: "Men Solid oversized cotton ",
      image: "Product_6.jpeg",
      Price: 438,
      quantity: 1,
      amount: 0,
    },
    {
      id: 7,
      brand: "The Indian Garage Co",
      name: "Oversized Casual TShirt ",
      image: "Product_7.jpeg",
      Price: 626,
      quantity: 1,
      amount: 0,
    },
    {
      id: 8,
      brand: "HERE & NOW ",
      name: "OverSized Sleeves TShirt ",
      image: "Product_8.jpeg",
      Price: 626,
      quantity: 1,
      amount: 0,
    },
  ],
};
export default products;
